Specify fields in MBTA V3 API request
MBTA added fields to their V3 API. I was getting an error when running
database migrations with migrate.py:

```
~/dev/mbtaccess dev* 11s
venv ❯ python migrate.py
Traceback (most recent call last):
  File "migrate.py", line 34, in <module>
    main()
  File "migrate.py", line 27, in main
    all_stops = Stop.from_api('https://api-v3.mbta.com/stops')
  File "/Users/brendon/dev/mbtaccess/models.py", line 113, in from_api
    output.append(cls(**d))
TypeError: __init__() got an unexpected keyword argument 'at_street'
```

The most stable solution is to specify fields in the URL query string,
such as https://api-v3.mbta.com/stops?fields[stop]=stop_id,name.

The new fields could also be added to Stop.__init__ in models.py,
but the code could continue breaking as fields are added to the API.